### ISSUE TITLE
Wallet location instructions need update?

### ISSUE THREAD

**Issue by AdamISZ** [openoms/joininbox#1]
See https://github.com/openoms/joininbox/blob/master/scripts/info.importwallet.sh#L63

**Comment by openoms** [comment]
Thank you for looking through.

I have left the path of the old versions there in case someone would want to migrate from an out of date version.

Agree that new wallets should be kept at `~/.joinmarket/wallets`.

The `~/.joinmarket` directory is one symlinked from the disk (HDD/SSD) on the RaspiBlitz so wallets and settings there are persisted and recovered during SDcard (OS) updates.
