### ISSUE TITLE
Should update git commit of bitcoin-scripts

### ISSUE THREAD

**Issue by kristapsk** [openoms/joininbox#119]
Noticed you are still using commit `9919d7410106aa99e64b605b4c7e836fe629d010` from Dec 3, 2021 for https://github.com/kristapsk/bitcoin-scripts. There have been some bugfixes, improvements and optimizations for `checktransaction.sh`. Should update to currently most recent commit.

**Comment by Willybroseur** [comment]
> Noticed you are still using commit `9919d7410106aa99e64b605b4c7e836fe629d010` from Dec 3, 2021 for https://github.com/kristapsk/bitcoin-scripts. There have been some bugfixes, improvements and optimizations for `checktransaction.sh`. Should update to currently most recent commit.
