### ISSUE TITLE
joinmarket user not accepting PASSWORD_B

### ISSUE THREAD

**Issue by bitsam** [openoms/joininbox#19]
when trying to connect to the QTGUI from Windows, I have configured a new Putty session and enabled X11 forwarding and the autologin as user: joinmarket. However, this session does not accept PASSWORD_B or any other password I have configured.

Also can you advise if I need to add any other details on the X11 setting page, such as X display location?

**Comment by openoms** [comment]
try logging in with simple ssh to `joinmarket@RASPIBLITZ_IP` to test the password.
It is the same password as in your bitcoin.conf as `rpcpassword` and also joinmarket.cfg as `rpc_pass`
The settings are as described, no need to set anything else.

**Comment by bitsam** [comment]
when trying a simple ssh as mentioned above i get the error message " Permission denied, please try again. " 

When normally logged into my raspiblitz, running # jm from the command prompt loads the joinbox and joinmarket applet. when i quit the joinbox menu I am then at the command prompt of the user joinmarket and can run the qtgui, but I am still having trouble with Xming which I will start another issue report on. btw, the command prompt is below.

(jmvenv) joinmarket@RASPIBLITZ IP:~/joinmarket-clientserver/scripts $

I know how to get back to the raspiblitz menu, but it just seems like there is a different password being used or the joinmarket user does not have permissions to launch an ssh session??

**Comment by bitsam** [comment]
It could be the way i set it up, I may have installed joinmarket from the command line before installing joinbox

**Comment by openoms** [comment]
The passfor for the `joinmarket` user is set up during the creation of the user here: https://github.com/rootzoll/raspiblitz/blob/82e0d6c3714ce1b2878780c4bdef72a6417f71c7/home.admin/config.scripts/bonus.joinmarket.sh#L67

Try to reinstall JoinMarket from the RaspiBlitz SERVICES menu so the user is recreated (JM wallets and settings are preserved).

**Comment by bitsam** [comment]
re-install from the Raspiblitz services fixed it.
