### ISSUE TITLE
QT GUI and Xming on windows

### ISSUE THREAD

**Issue by bitsam** [openoms/joininbox#20]
I have configured a putty session as per the instructions however I get the following error when running the command # qtgui.

# opening the JoinMarket-QT GUI with the command: '(jmvenv) python joinmarket-qt.py'
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.

Xming is running. In putty after enabling x11 forwarding, there is a field for X Display location. Am i meant to have an address here? If so what?

**Comment by bitsam** [comment]
I have tried re-installing joinmarket from the Joinbox menu however the problem still exists. I have confirmed that x11 forwarding works for the admin account on the raspiblitz. However I can not run the qtgui as the admin. As mensioned in my other issue, I am not able to ssh to the raspiblitz as the account joinmarket. How do I check that the joinmarket account has the correct permissions?

**Comment by openoms** [comment]
Try to reinstall Joinmarket from the Raspiblitz SERVICES menu.

**Comment by bitsam** [comment]
re-install from the Raspiblitz services fixed it.
