### ISSUE TITLE
missing dependency for ob-watcher

### ISSUE THREAD

**Issue by keblek** [openoms/joininbox#27]
![image](https://user-images.githubusercontent.com/68111648/109881396-825d3b80-7c78-11eb-9379-ca90ffe07a2f.png)

matplotlib not found

![image](https://user-images.githubusercontent.com/68111648/109881590-d8ca7a00-7c78-11eb-89fb-877912bf07f5.png)

**Comment by openoms** [comment]
yes, it is not installed by default, but could be part of the next SDcard release.

For now you can run manually:
`pip install matplotlib`
in the CLI with
`(jmvenv) $`
