### ISSUE TITLE
change label 

### ISSUE THREAD

**Issue by keblek** [openoms/joininbox#28]
![image](https://user-images.githubusercontent.com/68111648/109882969-fef11980-7c7a-11eb-9eb6-c86f2a4d2632.png)

Cancel should say disconnect, and go back to host instead of the shell. The last item on the menu takes you to the shell.

![image](https://user-images.githubusercontent.com/68111648/109883258-72932680-7c7b-11eb-9aa4-7dfc8b0cb312.png)

For the children it could say `Back` instead of `Cancel`

**Comment by openoms** [comment]
ok, cant test thsi by updating to the latest JBCOMMIT

**Comment by keblek** [comment]
Exit doesn't disconnect from joininbox, it exits to shell

**Comment by openoms** [comment]
Right, I know what you mean now. It could close the terminal. Will look into it.

**Comment by openoms** [comment]
I don't think the script running from the menu close the terminal.
Hence there are the instructions:
![image](https://user-images.githubusercontent.com/43343391/110115715-6491f280-7dae-11eb-8986-a019f93d84f2.png)

Let me know if you have a better solution.

**Comment by openoms** [comment]
The labels are changed. Feel free to reopen if there is a solution to exit the terminal.
