### ISSUE TITLE
link to docs in the menu

### ISSUE THREAD

**Issue by keblek** [openoms/joininbox#29]
https://github.com/JoinMarket-Org/joinmarket-clientserver/tree/master/docs

link to this and a QR code leading to this awesome video https://www.youtube.com/watch?v=zTCC86IUzWo so that I can easily watch it on my smartphone by scanning it or copy paste it to my browser

**Comment by openoms** [comment]
Please check:
https://github.com/openoms/joininbox/commit/1d523dc404db7c28ab1750583b3a864eac276fa6
and 
https://github.com/openoms/joininbox/commit/46637f9928db2a694089a765e192db5061cc91d9
Closing.
