### ISSUE TITLE
show what step needs to be taken next in the main menu

### ISSUE THREAD

**Issue by keblek** [openoms/joininbox#32]
1. Read docs
2. generate wallet
3. start yg

**Comment by openoms** [comment]
would be good to write down the workflow in detail for the readme or FAQ as it is more nuanced than that.

A tutorial to start from scratch is the way to go as there it is in the RaspiBlitz readme.

Not sure how to point to the next steps without putting popups everywhere. Might be the way to go after basic functions are built out.

**Comment by keblek** [comment]
Ok I can do a tutorial once I go through the entire workflow. A reminder that this is my first time with join market but I know what I want to achieve.

**Comment by openoms** [comment]
Adding a Quicktart menu option in https://github.com/openoms/joininbox/commit/e3c7af26e388c11977bbb7a0e5afc167b69b4768
Will be part of the next release
