### ISSUE TITLE
default to zero when going through INFO the first time

### ISSUE THREAD

**Issue by keblek** [openoms/joininbox#33]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/68111648/110044135-ea7b5280-7d48-11eb-8f05-beb0b6bd56b4.png">

**Comment by openoms** [comment]
I rather expose all the mixdepths for first time users as well.
There is no harm in funding other mixdepths first (or simultaneously). 
In any case the funding address suggested is from m0.

Also not sure if it is possible to prefill that field and also difficult to tell if it is opened the first time.
Too much complication in my opinion.

**Comment by keblek** [comment]
That makes sense, maybe then add a third option with a quick explanation? Or a link to the relevant doc. It's not intuitive that you can pick any depth, when starting out.

Also since there are only four choices, remove the text field altogether and let the user pick 0 to 4, explanation/docs, or go back.

**Comment by openoms** [comment]
Yes, agree that some radically simplified version of https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/USAGE.md#funding would be needed to which could link easily.

BTW do you know this video: https://www.keepitsimplebitcoin.com/joinmarket ?

**Comment by keblek** [comment]
I did not know they had one for join market! 

Maybe add the link to this as well.

**Comment by openoms** [comment]
Current state:
![image](https://user-images.githubusercontent.com/43343391/111150046-87c65a00-8585-11eb-9d61-803f19c9e03e.png)
![image](https://user-images.githubusercontent.com/43343391/111150078-9280ef00-8585-11eb-9bbb-3e3807529eb5.png)
