### ISSUE TITLE
add option to upgrade to Joinmarket 0.8.2

### ISSUE THREAD

**Issue by bitsam** [openoms/joininbox#34]
can you please add the option to update Joinmarket to v 0.8.2

**Comment by openoms** [comment]
Added here: https://github.com/openoms/joininbox/commit/d8f3e896dc5238b56429071e8894fa69cfe538e1
See this tweet: https://twitter.com/openoms/status/1369293432754208768

The new release of JoininBox is due today.

**Comment by openoms** [comment]
Now can also UPDATE to the v0.3.0 Joininbox release for JoinMarket v0.8.2
