### ISSUE TITLE
unzip: command not found when using the PRUNED option

### ISSUE THREAD

**Issue by openoms** [openoms/joininbox#35]
```
# The PGP signature and the hash of the downloaded snapshot is correct
# Exract and copy to /home/store/app-data/.bitcoin
# The folder /home/store/app-data is present already
sudo: unzip: command not found
```
Bitcoin Core starts to download the blockchain from the start as the snapshot is not extracted.

Solution:
run:
`sudo apt install unzip`
and choose the `PRUNED` option gain from the `CONFIG` menu.

**Comment by openoms** [comment]
can use the latest state on the default (master) branch to get this fixed:
`UPDATE` -> `ADVANCED` -> `JBCOMMIT`

**Comment by Silarous** [comment]
Tested and is now working.  Allowed the creation of a new wallet and import of old wallet from seed.
