### ISSUE TITLE
UX suggestion: In WALLET menu add option to deposit coins

### ISSUE THREAD

**Issue by peterflock** [openoms/joininbox#42]
Wallet management is in its own section and contains "list-history" option but "receive" money and "show balance" is in the INFO section.

I suggest to unify those options under one section for consistency.

**Comment by openoms** [comment]
Do you suggest getting rid of the INFO menu entirely and put it to the WALLET management?
Less menu options are probably better.
Agree that a DEPOSIT option could just show the first mixdepth, however one can deposit in any mixdepth...

It is hard to suggest best practices when JM can be used in different ways.

Generally depositing funds from different sources to different mixdepths is advised.

**Comment by peterflock** [comment]
I would consolidate all the "wallet/balance/transactions" option under one "Wallet" menu item. 

Not sure if INFO should be persisted, there is also some doc link.

**Comment by openoms** [comment]
good suggestion, thanks. Will change next.

**Comment by openoms** [comment]
closing with https://github.com/openoms/joininbox/commit/f3cc5ead332328157de67523abb960561a9845c6
will be part of the next release
