### ISSUE TITLE
UX freature: Add warning about inconfirmed UTXOs when doing CJ Send

### ISSUE THREAD

**Issue by peterflock** [openoms/joininbox#50]
When doing Send, swiping whole mixdepth, the unconfirmed outputs are omitted without warning.

It may be good to have some kind of warning that warn the user that no whole mixdepth will be used because unconfirmed UTXOs.

Also, it may be useful to see which UTXOs are unconfirmed in the overview of all mixdepths (INFO -> ALL)

**Comment by openoms** [comment]
For unconfirmed utxos see: https://github.com/openoms/joininbox/issues/45

Including them in a sweep would basically be a CPFP and would often need to bump another coinjoin so the miner fees set for the sweep would be insufficient.

I feel this is outside of the scope of joininbox for now.
