### ISSUE TITLE
# Error: wallet.jmdat file not found

### ISSUE THREAD

**Issue by redmac68** [openoms/joininbox#54]
Using the joininbox v0.4.0 menu on raspiblitz after jm shortcut, options that should open the wallet.jmdat file show "# Error: wallet.jmdat file not found".

**Comment by openoms** [comment]
there has been a bugfix in: https://github.com/openoms/joininbox/commit/21f5af1bd19f7f7cf659df13bc4dcde01d712005

can you please try updating again and if there is no change go for UPDATE -> ADVANCED -> RESET

**Comment by redmac68** [comment]
Thanks

**Comment by openoms** [comment]
Did the update solve this issue?

**Comment by redmac68** [comment]
Sorry, I should have provided my results.
The update alone didn't fix it, but the reset step did.

All good - thanks again.
