### ISSUE TITLE
Read wallet-tool.py output from STDOUT instead of STDERR

### ISSUE THREAD

**Issue by openoms** [openoms/joininbox#55]
Reminder to change this:
https://github.com/openoms/joininbox/blob/f05d05ad0b13b3cbc70db5d2953a2cde3f5abbdd/scripts/menu.quickstart.sh#L14

when https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/879 is merged and in a release,

**Comment by kristapsk** [comment]
Do you even need to remove that `2>&1`? Python exception stack traces still go to stderr. Unless you want to hide them from the user.

**Comment by openoms** [comment]
@kristapsk you are right, it can continue to be useful to show stderr and stdout as well. Closing this
