### ISSUE TITLE
Inconsistent information on default number of makers in send script

### ISSUE THREAD

**Issue by kev-vl** [openoms/joininbox#75]
Hi openoms, 

in the send script, when setting the number of maker, the user is shown "Leave empty for the default 8-10 (randomized)". However, when the user leaves it empty and carries on with the process, the user is shown "with 5-9 (randomized) makers".

These statements should be consistent and reflecting the actual default range used in the joinmarket sendpayment.py script.

**Comment by openoms** [comment]
correct, thanks for reporting
