### ISSUE TITLE
Disable automatic QT GUI in JoinMarket installation

### ISSUE THREAD

**Issue by asvdf** [openoms/joininbox#77]
Probably the main reason for someone to install joininbox is to have a "gui on the commandline", so I was expecting the QT packages needed by the QT GUI of JM would have been left out, yet I noticed they were automatically installed.
I would probably be a good idea to leave them out, or at most, have them optional via a commanline argument, calling the install script directly after `chmod +x build_joininbox.sh`, something like `./build_joininbox.sh --noqt`

**Comment by openoms** [comment]
If you get joininbox running you will see that there is an option to run the QT GUI remotely with `ssh -X`
This is quite popular and shall not be removed by default.
Will add option to the `build_joininbox.sh` to allow installing without the QT GUI dependencies and function altogether.
