### ISSUE TITLE
QR code for connecting to the JM wallet daemon

### ISSUE THREAD

**Issue by Fonta1n3** [openoms/joininbox#78]
Hello 👋 ,

I have finally got JM working well with FN via the new rpc api. It would be amazing if Joininbox could support the connection method. Here is what is needed:

- A hidden service controlling the jm wallet daemon port 28183
- A self signed cert.pem file in base64 text
- A QR code which displays the textual representation of a url in the following format:
`http://<hostname>.onion:28183?cert=<base64cert>`

Please let me know if you need any other info or have any questions, it would be great to have a place where I can recommend users easily connect FN to JM.

As a side note FN allows users to create tor auth keys, if they had the ability to add their pubkey to joininbox the connection would become much more secure than only relying on the self signed cert and onion.

Thanks for all that you do!

**Comment by openoms** [comment]
So this will need the joinmarket daemon running with a service as in: 
https://github.com/rootzoll/raspiblitz/blob/6d3af0cd8c79129d838cc91063e56c9d8c458ad7/home.admin/config.scripts/bonus.joinmarket-webui.sh#L134

Regarding the Tor auth keys there is a guide here which can be implemented: https://github.com/openoms/bitcoin-tutorials/blob/master/tor_hidden_service_example.md#add-client-authorization-optional

Question: how the Tor auth key would be shared? 
Should show an other QRcode and copy paste to Fully Noded or is there a more automated option to scan it in directly?
Is there a format preferred or just the key as a simple string?

**Comment by Fonta1n3** [comment]
> 
> Question: how the Tor auth key would be shared? 

FN creates the private key locally encrypts, saves it and allows you to either refresh your private key and/or export the public key in plain text and QR as a simple string.



> 
> Should show an other QRcode and copy paste to Fully Noded or is there a more automated option to scan it in directly?

FN does not allow the importing of tor auth private keys bc the tor recommended security practice states the client should create and hold the private key. 

However it would be a simple change to allow the importing of the private key to FN and I'm open to making that change incase users want to create their own auth keys. It would be via QR scan or paste.

> Is there a format preferred or just the key as a simple string?

Simple string as of now. The full descriptor with key. `descriptor:x25519:GSXUEQF46K6YEHOVCGD6NKLN5ZXDWX2SUIRIAGFKJ26KHYBHDYOA`

**Comment by openoms** [comment]
The option to connect Fully Noded with a QRcode now is in the Tools menu.

Can be tested by updating to the latest JBCOMMIT in the UPDATE -> ADVANCED menu until the next release.

**Comment by openoms** [comment]
closing as no reports of problems
will included in the next release
