### ISSUE TITLE
Error "BUILD FAILED --> PGP verification not OK" after installation

### ISSUE THREAD

**Issue by GerdOpp** [openoms/joininbox#80]
I run into a problem, installing Joininbox on the RPi4.

- I flashed the newest raspios: 2022-01-28-raspios-bullseye-armhf and logged into the RPi via ssh
- Then I followed your "Install JoininBox": https://github.com/openoms/joininbox/blob/master/README.md#install-joininbox
- The process ran through without interruption but in the end showed:"# !!! BUILD FAILED --> PGP verification not OK / signature(0) verify(0)"
Right before that, the last ouputs were:
2022-04-05 14:04:37 (16.4 MB/s) - ‘pgp_keys.asc’ saved [5335/5335]

gpg: directory '/home/joinmarket/.gnupg' created
gpg: keybox '/home/joinmarket/.gnupg/pubring.kbx' created
pub   rsa4096 2019-08-28 [SC] [expires: 2035-08-24]
      13C688DB5B9C745DE4D2E4545BFB77609B081B65
uid                      openoms <oms@tuta.io>
sub   rsa4096 2019-08-28 [E] [expires: 2035-08-24]
sub   rsa4096 2019-09-07 [S]

gpg: /home/joinmarket/.gnupg/trustdb.gpg: trustdb created
gpg: key 5BFB77609B081B65: public key "openoms <oms@tuta.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1

gpg: Signature made Thu 31 Mar 2022 07:41:16 AM BST
gpg:                using RSA key 4AEE18F83AFDEB23
gpg: Can't check signature: No public key
# goodSignature(0)
# correctKey(0)

**Comment by GerdOpp** [comment]
I repeated procedure with a newly flashed SDcard. After ssh login to the RPi I switched to root.
The outcome was the same error as before

**Comment by GerdOpp** [comment]
Maybe it would help to use another OS? I am totally free there. The raspberrypi should serve solely for JoininBox. I am open to all suggestions.

**Comment by openoms** [comment]
Yes, surely it would worth it to use the 64bit version f the RaspberryOS or for JoininBox only the even cleaner Debian release from raspi.debia.org as in: https://github.com/openoms/joininbox/blob/master/FAQ.md#download-and-verify-the-base-image (use the latest available build)

**Comment by openoms** [comment]
Actually the bullseye image is not yet tested so fixing this now:
```
###################################
# Identify the CPU and base image
###################################

# CPU: aarch64
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
# !!! FAIL !!!
# Base image cannot be detected or is not supported.
```

**Comment by openoms** [comment]
Reproduced the error on the 64bit RaspiOS as well, fix incoming.

**Comment by GerdOpp** [comment]
OK, thanks for the information. Then I will wait for your update-fix for the 64bit RaspiOS

Meanwhile I will test the Debian from https://raspi.debian.net/

**Comment by openoms** [comment]
ok, now the install script is also resetting to the latest version

please let me know of any further issues

**Comment by GerdOpp** [comment]
I used now the fixed install script with the 2022-01-28-raspios-bullseye-arm64.zip image. Installation went smoothly without errors!
Thanks for the quick fix!

Another question: Is it in this stand-alone version not possible to watch the order book locally? I got an error message.

**Comment by openoms** [comment]
It should work, please share the error message.

**Comment by openoms** [comment]
Is there a bitcoim node connected? Is yes how? did you prepare the remote node as in the FAQ?

**Comment by GerdOpp** [comment]
I connected my raspiblitz as in Prepare a bitcoin node
I have generated a new wallet and showed contents of md with DISPLAY
worked as expected

**Comment by openoms** [comment]
ok closing this as solved. If have further issues with the ob-watcher try to run it manually and/or share the output in a separate issue
