### ISSUE TITLE
Error in starting the local ob-watcher

### ISSUE THREAD

**Issue by GerdOpp** [openoms/joininbox#82]
I am having some trouble with the ob-watcher. Its giving an error when starting out of the menu.

**Comment by GerdOpp** [comment]
# Input which method (command) to use
getblockchaininfo
# Input the parameter(s) (optional)

# Reading the bitcoind RPC settings from the joinmarket.cfg
# Connecting over Tor...

{
  "result": {
    "chain": "main",
    "blocks": 730733,
    "headers": 730733,
    "bestblockhash": "0000000000000000000327df2a847f8d993f4efbf300c793a9c2de914571c5f4",
    "difficulty": 28587155782195.14,
    "mediantime": 1649269448,
    "verificationprogress": 0.9999984785883925,
    "initialblockdownload": false,
    "chainwork": "00000000000000000000000000000000000000002b91e72940591b3ffadc7404",
    "size_on_disk": 453846912047,
    "pruned": false,
    "softforks": {
      "bip34": {
        "type": "buried",
        "active": true,
        "height": 227931
      },
      "bip66": {
        "type": "buried",
        "active": true,
        "height": 363725
      },
      "bip65": {
        "type": "buried",
        "active": true,
        "height": 388381
      },
      "csv": {
        "type": "buried",
        "active": true,
        "height": 419328
      },
      "segwit": {
        "type": "buried",
        "active": true,
        "height": 481824
      },
      "taproot": {
        "type": "bip9",
        "bip9": {
          "status": "active",
          "start_time": 1619222400,
          "timeout": 1628640000,
          "since": 709632,
          "min_activation_height": 709632
        },
        "height": 709632,
        "active": true
      }
    },
    "warnings": ""
  },
  "error": null,
  "id": "# custom RPC"
}

Press ENTER to return to the menu...

**Comment by openoms** [comment]
> I am having some trouble with the ob-watcher. Its giving an error when starting out of the menu.

Would need the error to be able to help you.

**Comment by GerdOpp** [comment]
Thanks, but I think this issue has been solved by re-installing. So can be closed here.
